apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medic-booking-dev
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/yasminjammeli/medic-booking-platform.git
    targetRevision: main  
    path: helm/medic-booking
    helm:
      valueFiles:
        - values-dev.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: medic-booking-dev
  
  syncPolicy:
    automated:
      prune: true        # Supprime les ressources qui ne sont plus dans Git
      selfHeal: true     # Répare automatiquement les dérives
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m