apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: medic-booking
data:
  PORT: "4000"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:5001"
  USER_SERVICE_URL: "http://user-service:5000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: medic-booking
data:
  PORT: "5000"
  MONGO_URI: "mongodb://mongodb-service:27017/user_service"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-service-config
  namespace: medic-booking
data:
  PORT: "5001"
  MONGO_URI: "mongodb://mongodb-service:27017/appointment_service"
  USER_SERVICE_HOST: "user-service:50051"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: medic-booking
data:
  KAFKA_BROKER: "kafka-service:9092"
  KAFKA_TOPIC: "appointment-created"
