apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: medic-booking
type: Opaque
stringData:
  JWT_SECRET: e88bbd51a1406ea49d7b01bf56d19993b7d33138762d3796d130b9851907d05f  # ‚Üê CHANGEZ ICI

---
apiVersion: v1
kind: Secret
metadata:
  name: email-credentials
  namespace: medic-booking
type: Opaque
stringData:
  EMAIL_USER: jammeliyasmin@gmail.com  
  EMAIL_PASS: kekganqfchspmase  
