apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "medic-booking.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: email-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "medic-booking.labels" . | nindent 4 }}
type: Opaque
stringData:
  EMAIL_USER: {{ .Values.secrets.email.user | quote }}
  EMAIL_PASS: {{ .Values.secrets.email.password | quote }}